### PR TITLE
Fixed print_pose sample

### PR DESCRIPTION
**Pull request by AVGP**
The poses were not printed as the enum values weren't recognised

### CODE REVIEW

**Comment by Alushi** [comment]
i have a problem : struct.error : unpack requires a string argument of length 3.
in wich file i have to change pack.cmd to pack.command?

**Comment by love12734** [comment]
Start Myo for Linux
Find Myo device...
Connected.
Firmware version: 1.4.1670.2
Device name: Myo
Finished.
Traceback (most recent call last):
  File "test_myo.py", line 29, in <module>
    main()
  File "test_myo.py", line 18, in main
    myo.run()
  File "../lib/myo.py", line 50, in run
    self.ble.receive_packet(timeout)
  File "../lib/ble.py", line 23, in receive_packet
    self.notify_event(packet)
  File "../lib/ble.py", line 49, in notify_event
    listener.handle_data(p)
  File "../lib/device_listener.py", line 12, in handle_data
    data_type, value, address = unpack('3B', payload)
  File "../lib/utilities.py", line 7, in unpack
    return struct.unpack('<' + fmt, *args)
struct.error: unpack requires a string argument of length 3

I have a problem. same problem T_T

**Comment by AVGP** [comment]
Hmm, odd. I can't reproduce this here

**Comment by Alushi** [comment]
Yep, that's really odd. I just don't fucking know what's happening. Copy and paste, got serial and enum inside lib, and changed test_myo and print_pose_listener's lib directories. Have I done something wrong?

**Comment by Alushi** [comment]
now i'm using a raspbian and i had the this problem again "struct.error: unpack requires a string argument of length 3" ...

**Comment by Alushi** [comment]
i have solved the prob!!! i modified the device_listener.py : 

"from utilities import *
import struct

class DeviceListener(object):
 ....

if atribute == 0x23:
         value = 0
         address = 0
         data_type,value,address = struct.unpack(<'BBB' , data.payload[5:8])
        if data_type == 3:
.....
......
"

**Comment by AVGP** [comment]
@Alushi That sounds like a good idea for a pull request!

**Pull request merged**
